name: grew
description: "[2025학년도 전공종합설계PBLI 프로젝트]"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  go_router: ^16.2.4 # go_router
  flutter_riverpod: ^3.0.1 # Riverpod
  flutter_native_splash: ^2.4.6 # FlutterNativeSplash
  flutter_dotenv: ^6.0.0 # dotenv
  flutter_svg: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: AppleSDGothicNeo
      fonts:
        - asset: lib/core/assets/fonts/AppleSDGothicNeo-Light.ttf
          weight: 300
        - asset: lib/core/assets/fonts/AppleSDGothicNeo-Regular.ttf
          weight: 400
        - asset: lib/core/assets/fonts/AppleSDGothicNeo-Medium.ttf
          weight: 500
        - asset: lib/core/assets/fonts/AppleSDGothicNeo-SemiBold.ttf
          weight: 600
        - asset: lib/core/assets/fonts/AppleSDGothicNeo-Bold.ttf
          weight: 700
        - asset: lib/core/assets/fonts/AppleSDGothicNeo-ExtraBold.ttf
          weight: 800
    - family: Pretendard
      fonts:
        - asset: lib/core/assets/fonts/Pretendard-Light.ttf
          weight: 300
        - asset: lib/core/assets/fonts/Pretendard-Regular.ttf
          weight: 400
        - asset: lib/core/assets/fonts/Pretendard-Medium.ttf
          weight: 500
        - asset: lib/core/assets/fonts/Pretendard-SemiBold.ttf
          weight: 600
        - asset: lib/core/assets/fonts/Pretendard-Bold.ttf
          weight: 700
    - family: BlackHanSans
      fonts:
        - asset: lib/core/assets/fonts/BlackHanSans-Regular.ttf
          weight: 400

  assets:
    - lib/core/assets/icons/grew_logo_blue.png
    - lib/core/assets/icons/grew_logo_white.png
    - lib/core/assets/icons/right_arrow.svg
    - lib/core/assets/icons/bell_icon.svg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
